"""add amount

Revision ID: 22f34615beec
Revises: 8cc51fc8ad01
Create Date: 2024-11-13 15:11:36.193108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f34615beec'
down_revision: Union[str, None] = '8cc51fc8ad01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'amount')
    # ### end Alembic commands ###
